_base_: '../_base_/cityscapes_1024x1024.yml'

model:
  type: BiSeNetV3
  num_classes: 19

lr_scheduler:
  warmup_iters: 2000
  warmup_start_lr: 1.0e-5
  learning_rate: 0.003

#optimizer:
  #type: sgd
#  weight_decay: 0.0005
optimizer:
  type: AdamW

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 1, 1, 1, 1]

batch_size: 4
iters: 120000

#lr_scheduler:
#  type: PolynomialDecay
#  learning_rate: 0.05
#  end_lr: 0.0
#  power: 0.9
train_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.25
      max_scale_factor: 2.0
      scale_step_size: 0.05
    - type: RandomPaddingCrop
      crop_size: [1024, 1024]
#      crop_size: [1536, 768]
#      crop_size: [2048, 1024]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: Normalize
  mode: val