# _base_: '../_base_/cityscapes.yml'

batch_size: 16
iters: 40000

#optimizer:
#  weight_decay: 5.0e-4

lr_scheduler:
  type: PolynomialDecay
  warmup_iters: 200
  warmup_start_lr: 1.0e-5
  learning_rate: 0.003
#lr_scheduler:
# type: PolynomialDecay
# learning_rate: 0.003
# power: 0.9
# end_lr: 1.0e-5

#loss:
# types:
#   - type: OhemCrossEntropyLoss
#     min_kept: 690000
#   - type: DetailAggregateLoss
#   - type: OhemCrossEntropyLoss
#     min_kept: 690000
#   - type: OhemCrossEntropyLoss
#     min_kept: 690000
# coef: [1, 1, 1, 1]

loss:
  types:
    - type: CrossEntropyLoss
    - type: DetailAggregateLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 1, 1, 1]

optimizer:
  type: adam
#optimizer:
#  type: sgd
#  momentum: 0.9
#  weight_decay: 4.0e-5

model:
  type: G1_arm5
  num_classes: 11
#  pretrained: '/home/praiselab/YHT/home_2.4/output/a0501/G2_arm5-0.75-1-7600/best_model/model.pdparams'


train_dataset:
  type: Camvid
  dataset_root: datasets/camvid
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.5
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [960, 720]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Camvid
  dataset_root: datasets/camvid
  transforms:
    - type: Normalize
  mode: val

test_config:
  aug_eval: True
  scales: 1.0
