_base_: '../_base_/cityscapes.yml'

batch_size: 16
iters: 120000

#optimizer:
#  weight_decay: 5.0e-4

lr_scheduler:
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5
  learning_rate: 0.003
#lr_scheduler:
#  type: PolynomialDecay
#  learning_rate: 0.003
#  power: 0.9
#  end_lr: 1.0e-5

loss:
  types:
    - type: CrossEntropyLoss
    - type: DetailAggregateLoss
    - type: CrossEntropyLoss
#    - type: CrossEntropyLoss
  coef: [1, 1, 1]
#loss:
#  types:
#    - type: OhemCrossEntropyLoss
#      min_kept: 780000   # batch_size * 1024 * 512 // 16
#    - type: DetailAggregateLoss
#    - type: OhemCrossEntropyLoss
#      min_kept: 780000
#    - type: OhemCrossEntropyLoss
#      min_kept: 780000
#  coef: [1, 1, 1, 1]

optimizer:
  type: adam
#optimizer:
#  type: sgd
#  momentum: 0.9
#  weight_decay: 4.0e-5

model:
  type: G1A5_pag
  num_classes: 19
#  pretrained: '/home/praiselab/YHT/home_2.4/output/a0501/G2_arm5-0.5-1-7441/best_model/model.pdparams'

train_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.25
      max_scale_factor: 2.0
      scale_step_size: 0.15
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
#      crop_size: [1536, 768]
#      crop_size: [2048, 1024]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: Normalize
  mode: val

test_config:
  aug_eval: True
  scales: 1.0
