_base_: '../_base_/cityscapes.yml'

batch_size: 16
iters: 160000

optimizer:
  weight_decay: 5.0e-4

lr_scheduler:
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5
  learning_rate: 0.005
#lr_scheduler:
#  type: PolynomialDecay
#  learning_rate: 0.003
#  power: 0.9
#  end_lr: 1.0e-5

#loss:
#  types:
#    - type: OhemCrossEntropyLoss
##    - type: OhemCrossEntropyLoss
#    - type: OhemCrossEntropyLoss
#  coef: [1, 1]
loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 130000   # batch_size * 1024 * 512 // 16
    - type: DetailAggregateLoss
    - type: OhemCrossEntropyLoss
      min_kept: 130000
  coef: [1, 1, 1]
#optimizer:
#  type: adam

model:
  type: GSTDC4_00plus_DR
  num_classes: 19
  pretrained: '/home/praiselab/YHT/home_2.5/output/a0423/Gstdc4_0-0.5-1-6754/iter_160000/model.pdparams'

train_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.1
      max_scale_factor: 2.0
      scale_step_size: 0.1
    - type: RandomPaddingCrop
      crop_size: [1536, 768]
#      crop_size: [2048, 1024]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: Normalize
  mode: val

test_config:
  aug_eval: True
  scales: 1.0
