_base_: '../_base_/cityscapes.yml'

batch_size: 24
iters: 140000

model:
  type: STDCSeg
  backbone:
    type: STDC2
#    pretrained: https://bj.bcebos.com/paddleseg/dygraph/STDCNet1.tar.gz
    pretrained: '/mnt/HDD_2T/XJL/home_2.5/output/stdcseg/a0830/best_model/model.pdparams'
  pretrained: null

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 520000      # 32 * 1024*512 = 16770000
    - type: OhemCrossEntropyLoss
      min_kept: 520000
    - type: OhemCrossEntropyLoss
      min_kept: 520000
    - type: DetailAggregateLoss
  coef: [1, 1, 1, 1]

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5
  learning_rate: 0.01

train_dataset:
  type: Cityscapes
#  dataset_root: /home/praiselab/YHT/home_1/datasets/cityscapes
  dataset_root: /mnt/HDD_2T/XJL/home_2.5/datasets/cityscapes
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.125
      max_scale_factor: 1.5
      scale_step_size: 0.15
    - type: RandomPaddingCrop
#      crop_size: [1024, 512]
      crop_size: [1536, 768]
#      crop_size: [2048, 1024]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: /mnt/HDD_2T/XJL/home_2.5/datasets/cityscapes
  transforms:
    - type: Normalize
  mode: val