_base_: '../_base_/cityscapes.yml'

batch_size: 2
iters: 80000

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.03
  power: 0.9
  end_lr: 1.0e-5

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

optimizer:
  type: adam
  beta1: 0.9


model:
  type: LFCNet
  backbone:
    type: ResNet_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  enable_auxiliary_loss: False
  align_corners: False
  pretrained: null



train_dataset:
  type: Cityscapes
  dataset_root: data/cityscapes
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: data/cityscapes
  transforms:
    - type: Normalize
  mode: val




