_base_: '../_base_/cityscapes.yml'

batch_size: 16
iters: 80000

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  power: 0.9
  end_lr: 0

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

optimizer:
  type: adam

model:
  type: sh_lraspp
  backbone:
    type: ShuffleNetV2_x1
    # output_stride: 8
    # pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  enable_auxiliary_loss: False
  align_corners: False
  pretrained: null

train_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.25
      max_scale_factor: 2.0
      scale_step_size: 0.15
    - type: RandomPaddingCrop
#      crop_size: [1536, 768]
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: Normalize
  mode: val

